/* ═══════════════════════════════════════════════
   ANO TARA — lang.js
   English / Filipino translation strings
   ═══════════════════════════════════════════════ */
'use strict';

const LANG = {
  en: {
    // App
    appName: 'ano tara?',
    appSub: 'your planning companion',
    // Nav
    navHome: 'Home', navGroups: 'Groups', navCouple: 'Couple', navSettings: 'Settings',
    // Home
    greetSub: 'Good day,',
    netBalance: 'Net Balance',
    owedToYou: '↑ Owed to you',
    youOwe: '↓ You owe',
    yourGroups: 'Your Groups',
    newBtn: '+ New',
    happening: 'Activity',
    seeAll: 'See all',
    quickGroups: 'Groups', quickExpense: 'Add Expense', quickCouple: 'Couple', quickInvite: 'Invite',
    // Balance breakdown
    balBreakdownTitle: 'Balance Breakdown',
    balPerGroup: 'By Group',
    balPerPerson: 'By Person',
    requestPayment: 'Request Payment',
    sendMoney: 'Send Money',
    // Groups
    groupsTitle: 'Your Groups',
    addGroup: '+ New',
    jowaLabel: 'Ano Tara — Jowa',
    familiaLabel: 'Ano Tara — Mifamilia',
    berksLabel: 'Ano Tara — Berks',
    newGroupLabel: 'New Group',
    newGroupSub: 'Tap to create',
    coupleFinance: 'Couple Finance',
    familyEvent: 'Family Event',
    friendsHangout: 'Friends Hangout',
    tonight: 'TONIGHT',
    // Group Detail
    backBtn: 'Back',
    inviteBtn: 'Invite',
    tabTasks: 'Tasks', tabExpenses: 'Expenses', tabMembers: 'Members', tabSettle: 'Settle', tabMap: 'Map',
    tasksTitle: 'Tasks', addTask: '+ Add',
    expensesTitle: 'Expenses', addExpense: '+ Add',
    membersTitle: 'Members', inviteMember: '+ Invite',
    settleTitle: 'Smart Settlement ✨',
    settleHint: 'Simplified by Ano Tara',
    settleDesc: 'Instead of multiple payments, here\'s the simplest way to settle up.',
    settleOwes: 'Payments needed',
    sendReminders: 'Send Payment Reminders',
    genReceipt: 'Generate Receipt',
    mapTitle: 'Group Map',
    addPin: '+ Add Pin',
    // Task status
    statusDone: 'Done', statusProgress: 'In Progress', statusPending: 'Pending',
    setDone: '✅  Done', setProgress: '🔄  In Progress', setPending: '⏸  Pending',
    // Member status
    msHere: 'Here ✓', msWay: 'On the way', msLate: 'Running late', msCooking: 'Cooking 🍳',
    // Expenses
    budgetSpent: 'Total spent', budgetLabel: 'Budget', budgetRemaining: 'remaining',
    viewReceipt: '📄 View Receipt & Share',
    // Sharing
    shareTitle: 'Share & Invite',
    shareLinkLabel: 'Share Link',
    copyLink: 'Copy Link',
    shareMessenger: 'Share via Messenger',
    shareQR: 'Show QR Code',
    scanToJoin: 'Scan to join this group',
    // Couple
    coupleTitle: 'Couple Mode',
    coupleSub: 'couple finance + planning',
    thisMonth: 'This month together',
    savingsGoals: 'Savings Goals',
    newGoal: '+ Goal',
    sharedExpenses: 'Shared Expenses',
    activePoll: 'Active Poll',
    newPoll: '+ Poll',
    pairJowa: 'Pair with Partner',
    pairCode: 'Your Pairing Code',
    enterCode: 'Enter partner\'s code',
    pairBtn: 'Pair Now',
    synced: 'Synced',
    onTrack: 'On Track', almostThere: 'Almost!',
    // Receipt
    eventSummary: 'Event Summary',
    totalSpent: 'Total Spent',
    perPerson: 'Per Person',
    remaining: 'Remaining',
    paymentsNeeded: 'Settlements',
    shareMessengerBtn: 'Share via Messenger',
    savePDF: 'Save PDF',
    // Settings
    profileTitle: 'Profile',
    notifications: 'Notifications',
    paymentMethods: 'Payment Methods',
    monthlyReports: 'Monthly Reports',
    calendarSync: 'Calendar Sync',
    aiSmartLists: 'AI Smart Lists',
    comingSoon: 'Soon',
    rateApp: 'Rate the app',
    sendFeedback: 'Send Feedback',
    // Add entry modal
    addEntryTitle: 'Add Entry',
    addExpenseTitle: 'Add Expense',
    descLabel: 'Description',
    descPlaceholder: 'e.g. Dinner, Groceries, Uber…',
    amountLabel: 'Amount',
    amountPlaceholder: '₱ 0.00',
    paidByLabel: 'Paid by',
    splitLabel: 'Split method',
    splitEqual: 'Equally among all',
    splitCustom: 'Custom percentages',
    splitTwo: 'Between two people',
    splitFull: 'One person pays all',
    categoryLabel: 'Category',
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Add a note…',
    dateLabel: 'Date',
    photoLabel: 'Attach photo',
    splitPreview: 'Split Preview',
    addEntryBtn: 'Add Entry →',
    // Add task modal
    addTaskTitle: 'New Task',
    taskLabel: 'What needs to be done',
    taskPlaceholder: 'e.g. Buy ingredients, Book the venue…',
    assignLabel: 'Assign to',
    dueDateLabel: 'Due date (optional)',
    addTaskBtn: 'Add Task →',
    // New group modal
    newGroupTitle: 'New Group ✨',
    groupNameLabel: 'Group Name',
    groupNamePlaceholder: 'e.g. Palawan Trip, Reunion 2025…',
    groupTypeLabel: 'Type',
    budgetLabel2: 'Budget (optional)',
    createGroupBtn: 'Create Group →',
    typeJowa: 'Jowa', typeJowaSub: 'Couple finance',
    typeFamilia: 'Mifamilia', typeFamiliaSub: 'Family events',
    typeBerks: 'Berks', typeBerksSub: 'Friends hangout',
    typeTrip: 'Trip', typeTripSub: 'Travel planning',
    // Map
    mapPinTitle: 'Add Map Pin',
    pinNameLabel: 'Place name',
    pinNamePlaceholder: 'e.g. Parking Area A, Main Entrance…',
    pinTypeLabel: 'Pin type',
    pinMeetup: '📍 Meetup Spot', pinParking: '🅿️ Parking', pinEntrance: '🚪 Entrance', pinFood: '🍽️ Food Spot', pinPhoto: '📸 Photo Spot', pinOther: '📌 Other',
    pinNoteLabel: 'Note (optional)',
    pinNotePlaceholder: 'Directions or details…',
    addPinBtn: 'Drop Pin →',
    tapMapHint: 'Tap anywhere on the map to place a pin',
    // Balance breakdown modal
    owesThem: 'owes them',
    owesYou: 'owes you',
    settled: 'Settled ✓',
    // Toast
    linkCopied: '🔗 Link copied!',
    remindersSent: '📲 Reminders sent!',
    expenseAdded: '💸 Expense added!',
    taskAdded: '✅ Task added!',
    groupCreated: 'Group created!',
    pinAdded: '📍 Pin added to map!',
    codeCopied: '📋 Code copied!',
    pairSuccess: '💑 Paired successfully!',
  },

  fil: {
    appName: 'ano tara?',
    appSub: 'ang iyong planning companion',
    navHome: 'Home', navGroups: 'Grupo', navCouple: 'Jowa', navSettings: 'Settings',
    greetSub: 'Kumusta,',
    netBalance: 'Net Balance',
    owedToYou: '↑ Utang sa iyo',
    youOwe: '↓ Utang mo',
    yourGroups: 'Mga Grupo Mo',
    newBtn: '+ Bago',
    happening: 'Nangyayari',
    seeAll: 'Lahat',
    quickGroups: 'Grupo', quickExpense: 'Gastos', quickCouple: 'Jowa', quickInvite: 'Imbitahan',
    balBreakdownTitle: 'Breakdown ng Balance',
    balPerGroup: 'Bawat Grupo',
    balPerPerson: 'Bawat Tao',
    requestPayment: 'Humingi ng Bayad',
    sendMoney: 'Magpadala',
    groupsTitle: 'Mga Grupo',
    addGroup: '+ Bago',
    jowaLabel: 'Ano Tara — Jowa',
    familiaLabel: 'Ano Tara — Mifamilia',
    berksLabel: 'Ano Tara — Berks',
    newGroupLabel: 'Bagong Grupo',
    newGroupSub: 'Tap para gumawa',
    coupleFinance: 'Couple Finance',
    familyEvent: 'Family Event',
    friendsHangout: 'Barkada',
    tonight: 'NGAYONG GABI',
    backBtn: 'Bumalik',
    inviteBtn: 'Imbitahan',
    tabTasks: 'Tasks', tabExpenses: 'Gastos', tabMembers: 'Miyembro', tabSettle: 'Settle', tabMap: 'Mapa',
    tasksTitle: 'Mga Gawain', addTask: '+ Idagdag',
    expensesTitle: 'Gastusin', addExpense: '+ Idagdag',
    membersTitle: 'Miyembro', inviteMember: '+ Imbitahan',
    settleTitle: 'Smart Settlement ✨',
    settleHint: 'Pinasimple ng Ano Tara',
    settleDesc: 'Sa halip na maraming bayad, ito na lang ang pinakamadaling paraan.',
    settleOwes: 'Mga kailangang bayaran',
    sendReminders: 'Magpadala ng Reminder',
    genReceipt: 'Gumawa ng Receipt',
    mapTitle: 'Mapa ng Grupo',
    addPin: '+ Dagdag Pin',
    statusDone: 'Tapos', statusProgress: 'In Progress', statusPending: 'Pending',
    setDone: '✅  Tapos na', setProgress: '🔄  In Progress', setPending: '⏸  Pending',
    msHere: 'Nandito ✓', msWay: 'Papunta na', msLate: 'Naaantala', msCooking: 'Nagluluto 🍳',
    budgetSpent: 'Kabuuang ginastos', budgetLabel: 'Budget', budgetRemaining: 'natitira',
    viewReceipt: '📄 Tingnan ang Receipt',
    shareTitle: 'I-share at Imbitahan',
    shareLinkLabel: 'Share Link',
    copyLink: 'Kopyahin ang Link',
    shareMessenger: 'I-share sa Messenger',
    shareQR: 'Ipakita ang QR Code',
    scanToJoin: 'I-scan para sumali sa grupo',
    coupleTitle: 'Couple Mode',
    coupleSub: 'couple finance + planning',
    thisMonth: 'Ngayong buwan',
    savingsGoals: 'Savings Goals',
    newGoal: '+ Goal',
    sharedExpenses: 'Shared Expenses',
    activePoll: 'Aktibong Poll',
    newPoll: '+ Poll',
    pairJowa: 'I-pair ang Partner',
    pairCode: 'Pairing Code Mo',
    enterCode: 'Ilagay ang code ng partner',
    pairBtn: 'I-pair Na',
    synced: 'Naka-sync',
    onTrack: 'On Track', almostThere: 'Malapit na!',
    eventSummary: 'Buod ng Event',
    totalSpent: 'Kabuuang Ginastos',
    perPerson: 'Bawat Tao',
    remaining: 'Natitira',
    paymentsNeeded: 'Mga Kailangang Bayaran',
    shareMessengerBtn: 'I-share sa Messenger',
    savePDF: 'I-save bilang PDF',
    profileTitle: 'Profile',
    notifications: 'Notifications',
    paymentMethods: 'Payment Methods',
    monthlyReports: 'Monthly Reports',
    calendarSync: 'Calendar Sync',
    aiSmartLists: 'AI Smart Lists',
    comingSoon: 'Malapit na',
    rateApp: 'I-rate ang app',
    sendFeedback: 'Mag-feedback',
    addEntryTitle: 'Idagdag ang Entry',
    addExpenseTitle: 'Idagdag ang Gastos',
    descLabel: 'Paliwanag',
    descPlaceholder: 'hal. Dinner, Groceries, Uber…',
    amountLabel: 'Halaga',
    amountPlaceholder: '₱ 0.00',
    paidByLabel: 'Sino ang nagbayad',
    splitLabel: 'Paraan ng paghati',
    splitEqual: 'Pantay sa lahat',
    splitCustom: 'Custom na porsyento',
    splitTwo: 'Sa dalawang tao lang',
    splitFull: 'Isang tao ang babayad',
    categoryLabel: 'Kategorya',
    noteLabel: 'Tala (opsyonal)',
    notePlaceholder: 'Magdagdag ng tala…',
    dateLabel: 'Petsa',
    photoLabel: 'Mag-attach ng larawan',
    splitPreview: 'Preview ng Split',
    addEntryBtn: 'Idagdag →',
    addTaskTitle: 'Bagong Gawain',
    taskLabel: 'Ano ang dapat gawin',
    taskPlaceholder: 'hal. Bumili ng pagkain, I-book ang lugar…',
    assignLabel: 'I-assign kay',
    dueDateLabel: 'Deadline (opsyonal)',
    addTaskBtn: 'Idagdag ang Task →',
    newGroupTitle: 'Bagong Grupo ✨',
    groupNameLabel: 'Pangalan ng Grupo',
    groupNamePlaceholder: 'hal. Palawan Trip, Reunion 2025…',
    groupTypeLabel: 'Uri',
    budgetLabel2: 'Budget (opsyonal)',
    createGroupBtn: 'Gumawa ng Grupo →',
    typeJowa: 'Jowa', typeJowaSub: 'Couple finance',
    typeFamilia: 'Mifamilia', typeFamiliaSub: 'Family events',
    typeBerks: 'Berks', typeBerksSub: 'Barkada',
    typeTrip: 'Trip', typeTripSub: 'Travel planning',
    mapPinTitle: 'Dagdag ng Pin sa Mapa',
    pinNameLabel: 'Pangalan ng lugar',
    pinNamePlaceholder: 'hal. Parking Area A, Main Entrance…',
    pinTypeLabel: 'Uri ng pin',
    pinMeetup: '📍 Lugar ng Pagtitipon', pinParking: '🅿️ Parking', pinEntrance: '🚪 Pasukan', pinFood: '🍽️ Kainan', pinPhoto: '📸 Photo Spot', pinOther: '📌 Iba pa',
    pinNoteLabel: 'Tala (opsyonal)',
    pinNotePlaceholder: 'Direksyon o detalye…',
    addPinBtn: 'I-drop ang Pin →',
    tapMapHint: 'I-tap ang mapa para maglagay ng pin',
    owesThem: 'may utang sa kanila',
    owesYou: 'may utang sa iyo',
    settled: 'Bayad na ✓',
    linkCopied: '🔗 Link na-copy!',
    remindersSent: '📲 Mga reminder na-send!',
    expenseAdded: '💸 Gastos na-dagdag!',
    taskAdded: '✅ Task na-dagdag!',
    groupCreated: 'Grupo na-gawa!',
    pinAdded: '📍 Pin na-dagdag sa mapa!',
    codeCopied: '📋 Code na-copy!',
    pairSuccess: '💑 Na-pair na!',
  }
};

window.LANG = LANG;
